// Phase 4 — read-back parity verifier. After a live import, GET_COURSE the new
// course and structurally compare it to the archived source. Both sides are
// GET_COURSE documents, so a faithfully-copied block is identical EXCEPT for the
// things that legitimately change: client/server ids, uploaded media keys, and
// server-owned/timestamp fields. We canonicalize those away and report only real
// divergences — the true "did it round-trip?" check that the plan-based fidelity
// report can't give (it only knows what we intended to send, not what came back).
//
// Pure + deterministic; the orchestrator feeds it the two docs + the import flags.

import type { GetCourseDocument, Lesson, Block } from '@/shared/types/rise';
import { classifyString } from '@/core/census/scan';
import { extractUploadedKeys } from '@/core/assets/keys';
import { looksLikeClientId } from './ids';
import { orderLessons } from './plan';
import type { ManualFlag } from './executor';

// Fields the server assigns / that are inherently volatile between two copies —
// dropped before comparing (an id mismatch is expected, not a fidelity defect).
const VOLATILE = new Set([
  'id',
  'courseId',
  'lessonId',
  'globalBlockId',
  'originalId',
  'createdAt',
  'updatedAt',
  'contentUpdatedAt',
  'lastUpdatedBy',
  'transferredAt',
  'duplicatedFromId',
  'isNewlyInserted',
  'isPartnerContentAuthor',
  'pendingItemId',
  'version',
  'order',
  'author',
  'selectedAuthorId',
  'experiments',
  'metadata',
  'position',
  'deleted',
  'ready',
  // Server-DERIVED media delivery fields — regenerated by upload/CRUSH/TRANSCODE,
  // so they won't round-trip identically. Parity cares that the media KEY is
  // present (tokenized to #media), not these derivatives.
  'crushedKey',
  'useCrushedKey',
  'isSkipCrush',
  'sourcedFrom',
  'originalUrl',
  'thumbnail',
]);

// Long opaque server ids (course/lesson) aren't lowercase cuids — match them too
// so they normalize to the same token on both sides.
const RE_SERVER_ID = /^[A-Za-z0-9_-]{20,}$/;

function isIdLike(s: string): boolean {
  return looksLikeClientId(s) || RE_SERVER_ID.test(s);
}

function normalizeString(s: string): string {
  const kind = classifyString(s);
  if (kind && kind.startsWith('media-')) {
    // Any uploaded media key (old or new) → a presence token; we verify the slot
    // is filled, not the exact key (which is always remapped).
    return extractUploadedKeys(s).length ? '#media' : s;
  }
  // CDN / embed URLs are kept verbatim (they must round-trip exactly).
  if (kind === 'cdn' || kind === 'embed') return s;
  if (isIdLike(s)) return '#id';
  // Collapse insignificant whitespace (HTML/text re-serialization differences).
  return s.replace(/\s+/g, ' ').trim();
}

/** Canonicalize a value: drop volatile keys, tokenize ids/media, normalize text,
 *  sort object keys (so key-order differences don't show as diffs). */
export function canonicalize(node: unknown): unknown {
  if (node === null || node === undefined) return null;
  if (typeof node === 'string') return normalizeString(node);
  if (typeof node !== 'object') return node;
  if (Array.isArray(node)) return node.map(canonicalize);
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(node as Record<string, unknown>).sort()) {
    if (VOLATILE.has(k)) continue;
    out[k] = canonicalize((node as Record<string, unknown>)[k]);
  }
  return out;
}

export type ParityKind =
  | 'missing-lesson'
  | 'extra-lesson'
  | 'missing-block'
  | 'extra-block'
  | 'block-type-changed'
  | 'content-changed'
  | 'media-missing'
  | 'course-field-changed';

export interface ParityIssue {
  kind: ParityKind;
  /** Human path, e.g. `lessons[2] (Quiz) / blocks[5] interactive/tabs`. */
  path: string;
  detail?: string;
  /** Whether this divergence was expected (a flagged/unsupported case). */
  expected?: boolean;
}

export interface ParityReport {
  ok: boolean;
  lessons: { source: number; target: number };
  blocks: { source: number; target: number; compared: number };
  /** Real, unexpected divergences (drive ok=false). */
  issues: ParityIssue[];
  /** Expected divergences (flagged media not carried, draw-from-bank random draw). */
  expectedDivergences: ParityIssue[];
}

// Order lessons by the course's authoritative ordered lesson-id list
// (`course.lessons`) — the SAME ordering the plan builds with. ⚠ Do NOT sort by
// `position`: that field scrambles a real course (the very reason the plan stopped
// using it). Sorting either side by position aligns source-vs-target in different
// orders and manufactures phantom block-type-changed / missing-block divergences.
function orderedLessons(doc: GetCourseDocument): Lesson[] {
  const ls = Array.isArray(doc.lessons) ? doc.lessons : [];
  const orderField = (doc.course as Record<string, unknown> | undefined)?.lessons;
  return orderLessons(ls, orderField);
}

/**
 * Course-level fields the read-back verifies, one canonicalized diff each.
 * Everything the importer WRITES is here (title, description, theme, the four
 * image objects) plus the course settings scalars — which the importer does NOT
 * migrate yet, so a source with non-default settings reports honest
 * `course-field-changed` divergences instead of passing silently.
 *
 * Deliberately absent:
 *  - `labelSetId` — documented gap (monolingual label sets unmigrated); pure noise.
 *  - `l10n.showLocaleSelector` — already a manual flag (`locale-selector`).
 *  - `exportSettings`, `fonts`, `typefaces`, `lessons`, ids/timestamps — target
 *    lifecycle / covered elsewhere (typeface ids canonicalize to #id anyway).
 */
const COURSE_FIELDS = [
  'title',
  'description',
  'theme',
  'coverImage',
  'cardImage',
  'media', // the cover-page logo
  'lessonHeaderImage',
  'blockBackgroundImage',
  'overlayNavigationImage',
  // Settings scalars — see COURSE_SETTINGS_FIELDS below:
  'sidebarMode',
  'navigationMode',
  'showLessonCount',
  'showNavigationButtons',
  'allowSearch',
  'allowCopy',
  'animateBlockEntrance',
  'markComplete',
  'enableVideoPlaybackSpeed',
  'color',
  'aiTutorConfig',
] as const;

/** Course settings the importer does NOT migrate yet (documented gap — the
 *  write is captured, `UPDATE_COURSE_DEBOUNCE {id, settings}`, just not built).
 *  Divergences here are verified and REPORTED, but routed to the expected
 *  bucket: they are a known limitation of the tool, not an unexpected fidelity
 *  failure, so they must not mark an otherwise-faithful course `partial`.
 *  Remove a field from this list the moment its migration ships. */
const COURSE_SETTINGS_FIELDS: ReadonlySet<string> = new Set([
  'sidebarMode',
  'navigationMode',
  'showLessonCount',
  'showNavigationButtons',
  'allowSearch',
  'allowCopy',
  'animateBlockEntrance',
  'markComplete',
  'enableVideoPlaybackSpeed',
  'color',
  'aiTutorConfig',
]);

/** Empty-equivalence for course fields: a fresh course carries `{}`/null/'' in
 *  slots the source may hold as any OTHER of those — none is a divergence. An
 *  object/array is empty when every leaf is. */
function isDeepEmpty(v: unknown): boolean {
  if (v === null || v === undefined || v === '') return true;
  if (Array.isArray(v)) return v.every(isDeepEmpty);
  if (typeof v === 'object') {
    return Object.values(v as Record<string, unknown>).every(isDeepEmpty);
  }
  return false;
}

/** The course-field pass of verifyParity (see COURSE_FIELDS). */
function compareCourseFields(
  source: GetCourseDocument,
  target: GetCourseDocument,
  flaggedKeys: string[],
  issues: ParityIssue[],
  expected: ParityIssue[],
): void {
  const sc = (source.course ?? {}) as Record<string, unknown>;
  const tc = (target.course ?? {}) as Record<string, unknown>;
  // The four course-image slots: every new shell gets a RANDOM built-in cover
  // (capture-confirmed), and no captured write clears an image slot — so when
  // the SOURCE has no image there, the target keeping Rise's default is
  // unavoidable and expected, not a fidelity failure.
  const IMAGE_FIELDS = new Set(['coverImage', 'cardImage', 'media', 'lessonHeaderImage']);
  for (const f of COURSE_FIELDS) {
    const sv = sc[f];
    const tv = tc[f];
    if (isDeepEmpty(sv) && isDeepEmpty(tv)) continue;
    const a = canonicalize(sv);
    const b = canonicalize(tv);
    if (JSON.stringify(a) === JSON.stringify(b)) continue;
    const raw = JSON.stringify(sv ?? null);
    const isSettingsGap = COURSE_SETTINGS_FIELDS.has(f);
    const isDefaultImage = IMAGE_FIELDS.has(f) && isDeepEmpty(sv) && !isDeepEmpty(tv);
    const isExpected =
      isSettingsGap || isDefaultImage || flaggedKeys.some((k) => raw.includes(k));
    const diffs = { mediaMissing: [] as string[], changed: [] as string[] };
    collectLeafDiffs(a, b, f, diffs);
    const detailPaths = [...diffs.changed, ...diffs.mediaMissing];
    const detail =
      detailPaths.length > 0
        ? `${detailPaths.length} field(s) differ: ${detailPaths.slice(0, 6).join(', ')}${detailPaths.length > 6 ? ', …' : ''}`
        : `source ${JSON.stringify(a)?.slice(0, 80)} → target ${JSON.stringify(b)?.slice(0, 80)}`;
    (isExpected ? expected : issues).push({
      kind: 'course-field-changed',
      path: `course.${f}`,
      detail: isSettingsGap
        ? `${detail} (course settings are not migrated yet — known gap; set manually)`
        : isDefaultImage
          ? `${detail} (source has no ${f}; the target keeps Rise's random default — no captured write clears an image slot)`
          : detail,
      ...(isExpected ? { expected: true } : {}),
    });
  }
}

function blockKey(b: Block): string {
  return `${b.family ?? '?'}/${b.variant ?? b.type ?? '?'}`;
}

/** Collect leaf-level diffs between two canonical values, classifying a
 *  source-has-media / target-empty diff as `media-missing` (often expected). */
function collectLeafDiffs(
  a: unknown,
  b: unknown,
  path: string,
  out: { mediaMissing: string[]; changed: string[] },
): void {
  if (JSON.stringify(a) === JSON.stringify(b)) return;
  const aMedia = a === '#media';
  const bEmpty = b === '' || b === null || b === undefined;
  if (aMedia && bEmpty) {
    out.mediaMissing.push(path);
    return;
  }
  // Recurse into objects/arrays to localize the diff; leaf mismatch → changed.
  if (
    a && b && typeof a === 'object' && typeof b === 'object' &&
    Array.isArray(a) === Array.isArray(b)
  ) {
    if (Array.isArray(a) && Array.isArray(b)) {
      const n = Math.max(a.length, b.length);
      for (let i = 0; i < n; i++) collectLeafDiffs(a[i], b[i], `${path}[${i}]`, out);
      return;
    }
    const ao = a as Record<string, unknown>;
    const bo = b as Record<string, unknown>;
    for (const k of new Set([...Object.keys(ao), ...Object.keys(bo)])) {
      collectLeafDiffs(ao[k], bo[k], path ? `${path}.${k}` : k, out);
    }
    return;
  }
  out.changed.push(path);
}

/**
 * Compare an archived source course to a read-back target course. `flags` are
 * the import's manual-handling flags (storyline / orphan / unsupported media /
 * draw-from-bank) — divergences attributable to them are reported as *expected*
 * rather than failures.
 */
export function verifyParity(
  source: GetCourseDocument,
  target: GetCourseDocument,
  flags: ManualFlag[] = [],
): ParityReport {
  const sl = orderedLessons(source);
  const tl = orderedLessons(target);
  const issues: ParityIssue[] = [];
  const expected: ParityIssue[] = [];

  // Media tolerance is PER-BLOCK: a block tolerates a media-missing divergence
  // only when the import flagged THAT block (storyline/orphan, by block id) or
  // flagged a key this block's source actually contains (oversize/unsupported
  // flags carry a sourceKey but not always a block id). A course-level flag
  // (theme/cover/bank media) must never excuse a media loss on an unrelated
  // block — that masked real per-block failures course-wide.
  const flaggedBlockIds = new Set(
    flags.filter((f) => f.sourceBlockId).map((f) => f.sourceBlockId),
  );
  const flaggedKeys = flags
    .map((f) => f.sourceKey)
    .filter((k): k is string => !!k);

  // Course-level fields first (theme, images, settings, title/description) —
  // the lesson/block walk below never sees them.
  compareCourseFields(source, target, flaggedKeys, issues, expected);

  let blocksSource = 0;
  let blocksTarget = 0;
  let compared = 0;

  const nL = Math.max(sl.length, tl.length);
  for (let i = 0; i < nL; i++) {
    const s = sl[i];
    const t = tl[i];
    const label = `lessons[${i}]${typeof s?.title === 'string' && s.title ? ` (${s.title})` : ''}`;
    if (s && !t) {
      issues.push({ kind: 'missing-lesson', path: label, detail: 'lesson absent on target' });
      blocksSource += (s.items?.length ?? 0);
      continue;
    }
    if (!s && t) {
      issues.push({ kind: 'extra-lesson', path: `lessons[${i}]`, detail: 'unexpected lesson on target' });
      blocksTarget += (t.items?.length ?? 0);
      continue;
    }
    if (!s || !t) continue;

    if ((s.type ?? 'blocks') !== (t.type ?? 'blocks')) {
      issues.push({
        kind: 'content-changed',
        path: label,
        detail: `lesson type ${s.type} → ${t.type}`,
      });
    }

    const sb = (s.items ?? []) as Block[];
    const tb = (t.items ?? []) as Block[];
    blocksSource += sb.length;
    blocksTarget += tb.length;

    const nB = Math.max(sb.length, tb.length);
    for (let j = 0; j < nB; j++) {
      const a = sb[j];
      const b = tb[j];
      const bpath = `${label} / blocks[${j}]${a ? ` ${blockKey(a)}` : ''}`;
      if (a && !b) {
        issues.push({ kind: 'missing-block', path: bpath, detail: 'block absent on target' });
        continue;
      }
      if (!a && b) {
        issues.push({ kind: 'extra-block', path: `${label} / blocks[${j}] ${blockKey(b)}`, detail: 'unexpected block on target' });
        continue;
      }
      if (!a || !b) continue;
      compared++;

      if (blockKey(a) !== blockKey(b)) {
        issues.push({ kind: 'block-type-changed', path: bpath, detail: `${blockKey(a)} → ${blockKey(b)}` });
        continue;
      }

      const isDrawFromBank = blockKey(a) === 'knowledgeCheck/draw from question bank';
      const aRaw = JSON.stringify(a);
      const mediaTolerant =
        (a.id !== undefined && flaggedBlockIds.has(a.id)) ||
        flaggedKeys.some((k) => aRaw.includes(k));

      const diffs = { mediaMissing: [] as string[], changed: [] as string[] };
      collectLeafDiffs(canonicalize(a), canonicalize(b), '', diffs);

      for (const p of diffs.mediaMissing) {
        (mediaTolerant ? expected : issues).push({
          kind: 'media-missing',
          path: `${bpath}.${p}`,
          detail: 'media present in source, empty on target',
          expected: mediaTolerant,
        });
      }
      if (diffs.changed.length) {
        // A draw-from-bank block's bound question set is a random draw → tolerate.
        const bucket = isDrawFromBank ? expected : issues;
        bucket.push({
          kind: 'content-changed',
          path: bpath,
          detail: `${diffs.changed.length} field(s) differ: ${diffs.changed.slice(0, 6).join(', ')}`,
          expected: isDrawFromBank,
        });
      }
    }
  }

  return {
    ok: issues.length === 0,
    lessons: { source: sl.length, target: tl.length },
    blocks: { source: blocksSource, target: blocksTarget, compared },
    issues,
    expectedDivergences: expected,
  };
}

export function parityReportToMarkdown(
  r: ParityReport,
  meta?: { title?: string; sourceCourseId?: string; newCourseId?: string },
): string {
  const lines: string[] = [];
  if (meta?.title || meta?.sourceCourseId) {
    lines.push(`# Parity — ${meta.title ?? meta.sourceCourseId}`);
    if (meta.sourceCourseId) lines.push(`- Source course: \`${meta.sourceCourseId}\``);
    if (meta.newCourseId) lines.push(`- Target course: \`${meta.newCourseId}\``);
    lines.push('');
  }
  lines.push(`## Read-back parity${r.ok ? ' — OK' : ' — DIVERGENCES'}`);
  lines.push(
    `- Lessons: ${r.lessons.source} source / ${r.lessons.target} target · ` +
      `Blocks: ${r.blocks.source} source / ${r.blocks.target} target (${r.blocks.compared} compared)`,
  );
  if (r.issues.length) {
    lines.push(`- **Unexpected divergences: ${r.issues.length}**`);
    for (const x of r.issues.slice(0, 25)) lines.push(`  - [${x.kind}] ${x.path}${x.detail ? ` — ${x.detail}` : ''}`);
  } else {
    lines.push('- Unexpected divergences: 0 ✓');
  }
  if (r.expectedDivergences.length) {
    lines.push(`- Expected divergences (flagged/random): ${r.expectedDivergences.length}`);
  }
  return lines.join('\n');
}

// --- Multi-language stack parity (docs/rise-multilang.md) --------------------

export type L10nParityKind =
  | 'missing-locale'
  | 'extra-locale'
  | 'missing-cell'
  | 'cell-changed'
  | 'extra-cell'
  | 'placeholder-cell'
  | 'labelset-binding';

export interface L10nParityIssue {
  kind: L10nParityKind;
  locale?: string;
  l10nId?: string;
  detail?: string;
}

export interface L10nParityReport {
  /** Divergences that were announced by the plan (flagged storyline cells the
   *  import deliberately does not copy) — reported, but they never fail the
   *  course. Mirrors ParityReport.expectedDivergences. */
  expected?: L10nParityIssue[];
  /** Conversion-era placeholder rows that survive in locales where the SOURCE
   *  holds no row (`placeholder-cell`): the AI conversion translated the
   *  `!importing:` title / `.` description / placeholder lesson-1 title into
   *  EVERY locale, and `set-stack-titles` overwrites only the locales the
   *  source actually has — the rest keep the AI'd placeholder text VISIBLY
   *  (the source falls back to its default language there; the target shows
   *  the junk instead). The captured cell-delete removes an id across ALL
   *  locales, so there is no per-locale delete to clean these with — how to
   *  resolve them (overwrite with the default-locale value vs. leave + fix by
   *  hand) is an OPEN operator decision; until then they are surfaced here
   *  and flagged, never hidden. */
  placeholderJunk?: L10nParityIssue[];
  ok: boolean;
  locales: { source: string[]; target: string[] };
  cells: { source: number; target: number; compared: number };
  issues: L10nParityIssue[];
}

/**
 * Read-back parity for a stack's translation tables: every source cell must
 * exist on the target (per locale) and match modulo the same canonicalization
 * parity uses elsewhere (media keys → #media tokens, ids tokenized, whitespace
 * collapsed). Course-level ids are aligned via a structural ref map (the
 * target's title/description/cover refs are its own — created by the
 * conversion); lesson/block cells keep the source ids verbatim, and lesson
 * TITLE refs are additionally aligned by lesson index (lesson 1 reuses the
 * pre-conversion placeholder's ref). Self-contained: derives the maps from the
 * two docs it is given.
 */
export function verifyL10nParity(
  source: GetCourseDocument,
  target: GetCourseDocument,
  opts: {
    /** `cellKey(l10nId, locale)` entries whose ABSENCE on the target is
     *  expected — the flagged storyline cells the planner deliberately does not
     *  copy (docs/rise-multilang.md §4.3b). Without this, every flagged stack
     *  import false-fails its language read-back on exactly those cells. */
    toleratedMissing?: Set<string>;
  } = {},
): L10nParityReport {
  const srcTables = source.l10n?.translations ?? {};
  const tgtTables = target.l10n?.translations ?? {};
  const srcLocales = Object.keys(srcTables);
  const tgtLocales = Object.keys(tgtTables);
  const issues: L10nParityIssue[] = [];
  const expected: L10nParityIssue[] = [];

  for (const code of srcLocales) {
    if (!tgtLocales.includes(code)) issues.push({ kind: 'missing-locale', locale: code });
  }
  for (const code of tgtLocales) {
    if (!srcLocales.includes(code)) issues.push({ kind: 'extra-locale', locale: code });
  }

  // source l10nId → target l10nId. Course-level refs map structurally; lesson
  // title refs map by lesson index; everything else maps to itself.
  const idMap = new Map<string, string>();
  const mapRefs = (s: unknown, t: unknown): void => {
    if (
      s && t &&
      typeof s === 'object' && typeof t === 'object' &&
      !Array.isArray(s) && !Array.isArray(t)
    ) {
      const sr = (s as Record<string, unknown>).l10nId;
      const tr = (t as Record<string, unknown>).l10nId;
      if (
        typeof sr === 'string' &&
        typeof tr === 'string' &&
        Object.keys(s as object).length === 1 &&
        Object.keys(t as object).length === 1
      ) {
        idMap.set(sr, tr);
        return;
      }
      for (const k of Object.keys(s as Record<string, unknown>)) {
        mapRefs(
          (s as Record<string, unknown>)[k],
          (t as Record<string, unknown>)[k],
        );
      }
    }
  };
  mapRefs(source.course ?? {}, target.course ?? {});
  const srcLessons = orderedLessons(source);
  const tgtLessons = orderedLessons(target);
  srcLessons.forEach((sl, i) => {
    const tl = tgtLessons[i];
    if (sl && tl) mapRefs({ t: sl.title }, { t: tl.title });
  });

  const mappedTargets = new Set(idMap.values());
  let sourceCells = 0;
  let targetCells = 0;
  let compared = 0;

  for (const [code, table] of Object.entries(srcTables)) {
    const tgtTable = tgtTables[code] ?? {};
    for (const [id, value] of Object.entries(table)) {
      sourceCells++;
      const tgtId = idMap.get(id) ?? id;
      const tgtValue = tgtTable[tgtId];
      if (tgtValue === undefined) {
        (opts.toleratedMissing?.has(`${id} ${code}`) ? expected : issues).push({
          kind: 'missing-cell',
          locale: code,
          l10nId: id,
        });
        continue;
      }
      compared++;
      const a = JSON.stringify(canonicalize(value));
      const b = JSON.stringify(canonicalize(tgtValue));
      if (a !== b) {
        issues.push({
          kind: 'cell-changed',
          locale: code,
          l10nId: id,
          detail: `source ${a.slice(0, 120)} ≠ target ${b.slice(0, 120)}`,
        });
      }
    }
  }

  // Target-only cells: ids that came neither from the source verbatim nor via
  // the ref map — placeholder-era leftovers the cleanup should have removed.
  const srcIds = new Set<string>();
  for (const table of Object.values(srcTables)) {
    for (const id of Object.keys(table)) srcIds.add(id);
  }
  // Inverse of idMap, to trace a mapped target id back to its source id.
  const srcIdByTarget = new Map<string, string>();
  for (const [s, t] of idMap) srcIdByTarget.set(t, s);
  const placeholderJunk: L10nParityIssue[] = [];
  for (const [code, table] of Object.entries(tgtTables)) {
    for (const [id, tgtValue] of Object.entries(table)) {
      targetCells++;
      if (!srcIds.has(id) && !mappedTargets.has(id)) {
        issues.push({ kind: 'extra-cell', locale: code, l10nId: id });
        continue;
      }
      // A known id, but in a locale the SOURCE has no row for: a conversion-era
      // placeholder translation (AI'd "!importing:" title / "." description).
      // The source renders that locale via default-locale fallback; the target
      // shows this junk instead. Surfaced separately (see the report field's
      // doc) — there is no captured per-locale delete to clean it with.
      const srcId = srcIdByTarget.get(id) ?? (srcIds.has(id) ? id : undefined);
      if (srcId !== undefined && srcTables[code]?.[srcId] === undefined) {
        placeholderJunk.push({
          kind: 'placeholder-cell',
          locale: code,
          l10nId: id,
          detail: `target holds ${JSON.stringify(tgtValue).slice(0, 80)}; source falls back to its default language here`,
        });
      }
    }
  }

  return {
    ok: issues.length === 0,
    locales: { source: srcLocales, target: tgtLocales },
    cells: { source: sourceCells, target: targetCells, compared },
    issues,
    ...(expected.length ? { expected } : {}),
    ...(placeholderJunk.length ? { placeholderJunk } : {}),
  };
}

export function l10nParityToMarkdown(r: L10nParityReport): string {
  const lines: string[] = [];
  lines.push(`## Language parity${r.ok ? ' — OK' : ' — DIVERGENCES'}`);
  if (r.expected?.length) {
    lines.push(
      `- ${r.expected.length} expected absence(s) (flagged storyline cells — not copied by design)`,
    );
  }
  if (r.placeholderJunk?.length) {
    lines.push(
      `- **⚠ ${r.placeholderJunk.length} placeholder cell(s) survive** in languages the source serves by fallback: ` +
        'the conversion AI-translated the provisional title/description into every language, and only the ' +
        'languages the source actually holds were overwritten. Those languages VISIBLY show the placeholder ' +
        'text (the source falls back to its default language there). Fix each by hand in the editor, or wait ' +
        'for the pending tooling decision (no per-locale cell delete exists in the captured API).',
    );
    for (const x of r.placeholderJunk.slice(0, 15)) {
      lines.push(`  - [${x.locale}] ${x.l10nId}${x.detail ? ` — ${x.detail}` : ''}`);
    }
  }
  lines.push(
    `- Languages: ${r.locales.source.join(', ') || '—'} (source) / ${r.locales.target.join(', ') || '—'} (target)`,
  );
  lines.push(
    `- Translation cells: ${r.cells.source} source / ${r.cells.target} target (${r.cells.compared} compared)`,
  );
  if (r.issues.length) {
    lines.push(`- **Divergences: ${r.issues.length}**`);
    for (const x of r.issues.slice(0, 25)) {
      lines.push(
        `  - [${x.kind}] ${x.locale ?? ''} ${x.l10nId ?? ''}${x.detail ? ` — ${x.detail}` : ''}`,
      );
    }
  } else {
    lines.push('- Divergences: 0 ✓');
  }
  return lines.join('\n');
}
