// Phase 4 — read-back parity verifier. After a live import, GET_COURSE the new
// course and structurally compare it to the archived source. Both sides are
// GET_COURSE documents, so a faithfully-copied block is identical EXCEPT for the
// things that legitimately change: client/server ids, uploaded media keys, and
// server-owned/timestamp fields. We canonicalize those away and report only real
// divergences — the true "did it round-trip?" check that the plan-based fidelity
// report can't give (it only knows what we intended to send, not what came back).
//
// Pure + deterministic; the orchestrator feeds it the two docs + the import flags.

import type { GetCourseDocument, Lesson, Block } from '@/shared/types/rise';
import { classifyString } from '@/core/census/scan';
import { extractUploadedKeys } from '@/core/assets/keys';
import { looksLikeClientId } from './ids';
import { orderLessons } from './plan';
import type { ManualFlag } from './executor';

/** Persisted with each import report. Bump whenever an older "completed"
 *  report is no longer sufficient proof under the current read-back contract. */
export const READ_BACK_POLICY_VERSION = 2;

// Fields the server assigns / that are inherently volatile between two copies —
// dropped before comparing (an id mismatch is expected, not a fidelity defect).
const VOLATILE = new Set([
  'id',
  'courseId',
  'lessonId',
  'globalBlockId',
  'originalId',
  'createdAt',
  'updatedAt',
  'contentUpdatedAt',
  'lastUpdatedBy',
  'transferredAt',
  'duplicatedFromId',
  'isNewlyInserted',
  'isPartnerContentAuthor',
  'pendingItemId',
  'version',
  'order',
  'author',
  'selectedAuthorId',
  'experiments',
  'metadata',
  'position',
  'deleted',
  'ready',
  // Server-DERIVED media delivery fields — regenerated by upload/CRUSH/TRANSCODE,
  // so they won't round-trip identically. Parity cares that the media KEY is
  // present (tokenized to #media), not these derivatives.
  'crushedKey',
  'useCrushedKey',
  'isSkipCrush',
  'sourcedFrom',
  'originalUrl',
  'thumbnail',
]);

// Long opaque server ids (course/lesson) aren't lowercase cuids — match them too
// so they normalize to the same token on both sides.
const RE_SERVER_ID = /^[A-Za-z0-9_-]{20,}$/;

function isIdLike(s: string): boolean {
  return looksLikeClientId(s) || RE_SERVER_ID.test(s);
}

function normalizeString(s: string): string {
  const kind = classifyString(s);
  if (kind && kind.startsWith('media-')) {
    // Any uploaded media key (old or new) → a presence token; we verify the slot
    // is filled, not the exact key (which is always remapped).
    return extractUploadedKeys(s).length ? '#media' : s;
  }
  // CDN / embed URLs are kept verbatim (they must round-trip exactly).
  if (kind === 'cdn' || kind === 'embed') return s;
  if (isIdLike(s)) return '#id';
  // Collapse insignificant whitespace (HTML/text re-serialization differences).
  return s.replace(/\s+/g, ' ').trim();
}

/** Canonicalize a value: drop volatile keys, tokenize ids/media, normalize text,
 *  sort object keys (so key-order differences don't show as diffs). */
export function canonicalize(node: unknown): unknown {
  if (node === null || node === undefined) return null;
  if (typeof node === 'string') return normalizeString(node);
  if (typeof node !== 'object') return node;
  if (Array.isArray(node)) return node.map(canonicalize);
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(node as Record<string, unknown>).sort()) {
    if (VOLATILE.has(k)) continue;
    out[k] = canonicalize((node as Record<string, unknown>)[k]);
  }
  return out;
}

export type ParityKind =
  | 'missing-lesson'
  | 'extra-lesson'
  | 'missing-block'
  | 'extra-block'
  | 'block-type-changed'
  | 'content-changed'
  | 'media-missing'
  | 'course-field-changed';

export interface ParityIssue {
  kind: ParityKind;
  /** Human path, e.g. `lessons[2] (Quiz) / blocks[5] interactive/tabs`. */
  path: string;
  detail?: string;
  /** Whether this divergence was expected (a flagged/unsupported case). */
  expected?: boolean;
}

export interface ParityReport {
  ok: boolean;
  lessons: { source: number; target: number };
  blocks: { source: number; target: number; compared: number };
  /** Blocking source/target divergences (drive ok=false). */
  issues: ParityIssue[];
  /** Expected divergences (flagged media not carried, draw-from-bank random draw). */
  expectedDivergences: ParityIssue[];
}

// Order lessons by the course's authoritative ordered lesson-id list
// (`course.lessons`) — the SAME ordering the plan builds with. ⚠ Do NOT sort by
// `position`: that field scrambles a real course (the very reason the plan stopped
// using it). Sorting either side by position aligns source-vs-target in different
// orders and manufactures phantom block-type-changed / missing-block divergences.
export function orderedLessons(doc: GetCourseDocument): Lesson[] {
  const ls = Array.isArray(doc.lessons) ? doc.lessons : [];
  const orderField = (doc.course as Record<string, unknown> | undefined)?.lessons;
  return orderLessons(ls, orderField);
}

/**
 * Course-level fields the read-back verifies, one canonicalized diff each.
 * Everything the importer WRITES is here (title, description, theme, the four
 * image objects) plus the complete course-settings surface currently present in
 * GET_COURSE. Settings are not written yet, so any source/target difference is
 * deliberately a BLOCKING `course-field-changed` divergence until that later
 * migration pass exists.
 *
 * Deliberately absent:
 *  - `labelSetId` — documented gap (monolingual label sets unmigrated); pure noise.
 *  - `l10n.showLocaleSelector` — already a manual flag (`locale-selector`).
 *  - `exportSettings`, `fonts`, `typefaces`, `lessons`, ids/timestamps — target
 *    lifecycle / covered elsewhere (typeface ids canonicalize to #id anyway).
 */
const COURSE_FIELDS = [
  'title',
  'description',
  'type',
  'theme',
  'coverImage',
  'cardImage',
  'media', // the cover-page logo
  'lessonHeaderImage',
  'blockBackgroundImage',
  'overlayNavigationImage',
  // Settings scalars — see COURSE_SETTINGS_FIELDS below:
  'sidebarMode',
  'navigationMode',
  'showLessonCount',
  'showNavigationButtons',
  'allowSearch',
  'allowCopy',
  'animateBlockEntrance',
  'markComplete',
  'enableVideoPlaybackSpeed',
  'color',
  'settings',
  'aiTutorConfig',
] as const;

/** Course settings the importer does NOT migrate yet. This set is only used to
 *  make the blocking report actionable; membership never excuses a mismatch.
 *  `settings` covers nested flags such as `aiTutorEnabled` and
 *  `isAIConceptToCourse`. Remove the annotation field-by-field as settings
 *  migration ships. */
const COURSE_SETTINGS_FIELDS: ReadonlySet<string> = new Set([
  'sidebarMode',
  'navigationMode',
  'showLessonCount',
  'showNavigationButtons',
  'allowSearch',
  'allowCopy',
  'animateBlockEntrance',
  'markComplete',
  'enableVideoPlaybackSpeed',
  'color',
  'settings',
  'aiTutorConfig',
]);

/** Empty-equivalence for course fields: a fresh course carries `{}`/null/'' in
 *  slots the source may hold as any OTHER of those — none is a divergence. An
 *  object/array is empty when every leaf is. */
function isDeepEmpty(v: unknown): boolean {
  if (v === null || v === undefined || v === '') return true;
  if (Array.isArray(v)) return v.every(isDeepEmpty);
  if (typeof v === 'object') {
    return Object.values(v as Record<string, unknown>).every(isDeepEmpty);
  }
  return false;
}

/** The course-field pass of verifyParity (see COURSE_FIELDS). */
function compareCourseFields(
  source: GetCourseDocument,
  target: GetCourseDocument,
  flaggedKeys: string[],
  issues: ParityIssue[],
  expected: ParityIssue[],
): void {
  const sc = (source.course ?? {}) as Record<string, unknown>;
  const tc = (target.course ?? {}) as Record<string, unknown>;
  // The four course-image slots: every new shell gets a RANDOM built-in cover
  // (capture-confirmed), and no captured write clears an image slot — so when
  // the SOURCE has no image there, the target keeping Rise's default is
  // unavoidable and expected, not a fidelity failure.
  const IMAGE_FIELDS = new Set(['coverImage', 'cardImage', 'media', 'lessonHeaderImage']);
  for (const f of COURSE_FIELDS) {
    const sv = sc[f];
    const tv = tc[f];
    if (isDeepEmpty(sv) && isDeepEmpty(tv)) continue;
    const a = canonicalize(sv);
    const b = canonicalize(tv);
    if (JSON.stringify(a) === JSON.stringify(b)) continue;
    const raw = JSON.stringify(sv ?? null);
    const isSettingsGap = COURSE_SETTINGS_FIELDS.has(f);
    const isDefaultImage = IMAGE_FIELDS.has(f) && isDeepEmpty(sv) && !isDeepEmpty(tv);
    const isExpected = isDefaultImage || flaggedKeys.some((k) => raw.includes(k));
    const diffs = { mediaMissing: [] as string[], changed: [] as string[] };
    collectLeafDiffs(a, b, f, diffs);
    const detailPaths = [...diffs.changed, ...diffs.mediaMissing];
    const detail =
      detailPaths.length > 0
        ? `${detailPaths.length} field(s) differ: ${detailPaths.slice(0, 6).join(', ')}${detailPaths.length > 6 ? ', …' : ''}`
        : `source ${JSON.stringify(a)?.slice(0, 80)} → target ${JSON.stringify(b)?.slice(0, 80)}`;
    (isExpected ? expected : issues).push({
      kind: 'course-field-changed',
      path: `course.${f}`,
      detail: isSettingsGap
        ? `${detail} (course setting is not migrated yet; parity cannot be confirmed)`
        : isDefaultImage
          ? `${detail} (source has no ${f}; the target keeps Rise's random default — no captured write clears an image slot)`
          : detail,
      ...(isExpected ? { expected: true } : {}),
    });
  }
}

function blockKey(b: Block): string {
  return `${b.family ?? '?'}/${b.variant ?? b.type ?? '?'}`;
}

/** Collect leaf-level diffs between two canonical values, classifying a
 *  source-has-media / target-empty diff as `media-missing` (often expected). */
function collectLeafDiffs(
  a: unknown,
  b: unknown,
  path: string,
  out: { mediaMissing: string[]; changed: string[] },
): void {
  if (JSON.stringify(a) === JSON.stringify(b)) return;
  const aMedia = a === '#media';
  const bEmpty = b === '' || b === null || b === undefined;
  if (aMedia && bEmpty) {
    out.mediaMissing.push(path);
    return;
  }
  // Recurse into objects/arrays to localize the diff; leaf mismatch → changed.
  if (
    a && b && typeof a === 'object' && typeof b === 'object' &&
    Array.isArray(a) === Array.isArray(b)
  ) {
    if (Array.isArray(a) && Array.isArray(b)) {
      const n = Math.max(a.length, b.length);
      for (let i = 0; i < n; i++) collectLeafDiffs(a[i], b[i], `${path}[${i}]`, out);
      return;
    }
    const ao = a as Record<string, unknown>;
    const bo = b as Record<string, unknown>;
    for (const k of new Set([...Object.keys(ao), ...Object.keys(bo)])) {
      collectLeafDiffs(ao[k], bo[k], path ? `${path}.${k}` : k, out);
    }
    return;
  }
  out.changed.push(path);
}

/**
 * Compare an archived source course to a read-back target course. `flags` are
 * the import's manual-handling flags (storyline / orphan / unsupported media /
 * draw-from-bank) — divergences attributable to them are reported as *expected*
 * rather than failures.
 */
export function verifyParity(
  source: GetCourseDocument,
  target: GetCourseDocument,
  flags: ManualFlag[] = [],
): ParityReport {
  const sl = orderedLessons(source);
  const tl = orderedLessons(target);
  const issues: ParityIssue[] = [];
  const expected: ParityIssue[] = [];

  // Media tolerance is PER-BLOCK: a block tolerates a media-missing divergence
  // only when the import flagged THAT block (storyline/orphan, by block id) or
  // flagged a key this block's source actually contains (oversize/unsupported
  // flags carry a sourceKey but not always a block id). A course-level flag
  // (theme/cover/bank media) must never excuse a media loss on an unrelated
  // block — that masked real per-block failures course-wide.
  const flaggedBlockIds = new Set(
    flags.filter((f) => f.sourceBlockId).map((f) => f.sourceBlockId),
  );
  const isExpectedReplacement = (lessonId: unknown, blockId: unknown): boolean =>
    typeof blockId === 'string' &&
    flags.some(
      (flag) =>
        flag.sourceBlockId === blockId &&
        flag.expectedReplacement === 'legacy-storyline' &&
        (!flag.sourceLessonId || flag.sourceLessonId === lessonId),
    );
  const flaggedKeys = flags
    .map((f) => f.sourceKey)
    .filter((k): k is string => !!k);

  // Course-level fields first (theme, images, settings, title/description) —
  // the lesson/block walk below never sees them.
  compareCourseFields(source, target, flaggedKeys, issues, expected);

  let blocksSource = 0;
  let blocksTarget = 0;
  let compared = 0;

  const nL = Math.max(sl.length, tl.length);
  for (let i = 0; i < nL; i++) {
    const s = sl[i];
    const t = tl[i];
    const label = `lessons[${i}]${typeof s?.title === 'string' && s.title ? ` (${s.title})` : ''}`;
    if (s && !t) {
      issues.push({ kind: 'missing-lesson', path: label, detail: 'lesson absent on target' });
      blocksSource += (s.items?.length ?? 0);
      continue;
    }
    if (!s && t) {
      issues.push({ kind: 'extra-lesson', path: `lessons[${i}]`, detail: 'unexpected lesson on target' });
      blocksTarget += (t.items?.length ?? 0);
      continue;
    }
    if (!s || !t) continue;

    if ((s.type ?? 'blocks') !== (t.type ?? 'blocks')) {
      issues.push({
        kind: 'content-changed',
        path: label,
        detail: `lesson type ${s.type} → ${t.type}`,
      });
    }

    const sb = (s.items ?? []) as Block[];
    const tb = (t.items ?? []) as Block[];
    blocksSource += sb.length;
    blocksTarget += tb.length;

    const nB = Math.max(sb.length, tb.length);
    for (let j = 0; j < nB; j++) {
      const a = sb[j];
      const b = tb[j];
      const bpath = `${label} / blocks[${j}]${a ? ` ${blockKey(a)}` : ''}`;
      if (a && !b) {
        issues.push({ kind: 'missing-block', path: bpath, detail: 'block absent on target' });
        continue;
      }
      if (!a && b) {
        issues.push({ kind: 'extra-block', path: `${label} / blocks[${j}] ${blockKey(b)}`, detail: 'unexpected block on target' });
        continue;
      }
      if (!a || !b) continue;
      compared++;

      if (blockKey(a) !== blockKey(b)) {
        const announced = isExpectedReplacement(s.id, a.id);
        (announced ? expected : issues).push({
          kind: 'block-type-changed',
          path: bpath,
          detail: `${blockKey(a)} → ${blockKey(b)}`,
          ...(announced ? { expected: true } : {}),
        });
        continue;
      }

      const isDrawFromBank = blockKey(a) === 'knowledgeCheck/draw from question bank';
      const aRaw = JSON.stringify(a);
      const mediaTolerant =
        (a.id !== undefined && flaggedBlockIds.has(a.id)) ||
        flaggedKeys.some((k) => aRaw.includes(k));

      const diffs = { mediaMissing: [] as string[], changed: [] as string[] };
      collectLeafDiffs(canonicalize(a), canonicalize(b), '', diffs);

      for (const p of diffs.mediaMissing) {
        (mediaTolerant ? expected : issues).push({
          kind: 'media-missing',
          path: `${bpath}.${p}`,
          detail: 'media present in source, empty on target',
          expected: mediaTolerant,
        });
      }
      if (diffs.changed.length) {
        // A draw-from-bank block's bound question set is a random draw → tolerate.
        const bucket = isDrawFromBank ? expected : issues;
        bucket.push({
          kind: 'content-changed',
          path: bpath,
          detail: `${diffs.changed.length} field(s) differ: ${diffs.changed.slice(0, 6).join(', ')}`,
          expected: isDrawFromBank,
        });
      }
    }
  }

  return {
    ok: issues.length === 0,
    lessons: { source: sl.length, target: tl.length },
    blocks: { source: blocksSource, target: blocksTarget, compared },
    issues,
    expectedDivergences: expected,
  };
}

export function parityReportToMarkdown(
  r: ParityReport,
  meta?: { title?: string; sourceCourseId?: string; newCourseId?: string },
): string {
  const lines: string[] = [];
  if (meta?.title || meta?.sourceCourseId) {
    lines.push(`# Parity — ${meta.title ?? meta.sourceCourseId}`);
    if (meta.sourceCourseId) lines.push(`- Source course: \`${meta.sourceCourseId}\``);
    if (meta.newCourseId) lines.push(`- Target course: \`${meta.newCourseId}\``);
    lines.push('');
  }
  lines.push(`## Read-back parity${r.ok ? ' — OK' : ' — DIVERGENCES'}`);
  lines.push(
    `- Lessons: ${r.lessons.source} source / ${r.lessons.target} target · ` +
      `Blocks: ${r.blocks.source} source / ${r.blocks.target} target (${r.blocks.compared} compared)`,
  );
  if (r.issues.length) {
    lines.push(`- **Blocking divergences: ${r.issues.length}**`);
    for (const x of r.issues.slice(0, 25)) lines.push(`  - [${x.kind}] ${x.path}${x.detail ? ` — ${x.detail}` : ''}`);
  } else {
    lines.push('- Blocking divergences: 0 ✓');
  }
  if (r.expectedDivergences.length) {
    lines.push(`- Expected divergences (flagged/random): ${r.expectedDivergences.length}`);
  }
  return lines.join('\n');
}


// --- Multi-language stack parity — split to ./verify-l10n (v0.9.0) ----------
// Re-exported here so the public surface of './verify' is unchanged.
export {
  verifyL10nParity,
  l10nParityToMarkdown,
  type L10nParityKind,
  type L10nParityIssue,
  type L10nParityReport,
} from './verify-l10n';
