// Phase 4 — read-back parity verifier. After a live import, GET_COURSE the new
// course and structurally compare it to the archived source. Both sides are
// GET_COURSE documents, so a faithfully-copied block is identical EXCEPT for the
// things that legitimately change: client/server ids, uploaded media keys, and
// server-owned/timestamp fields. We canonicalize those away and report only real
// divergences — the true "did it round-trip?" check that the plan-based fidelity
// report can't give (it only knows what we intended to send, not what came back).
//
// Pure + deterministic; the orchestrator feeds it the two docs + the import flags.

import type { GetCourseDocument, Lesson, Block } from '@/shared/types/rise';
import { classifyString } from '@/core/census/scan';
import { extractUploadedKeys } from '@/core/assets/keys';
import { looksLikeClientId } from './ids';
import { orderLessons } from './plan';
import type { ManualFlag } from './executor';

// Fields the server assigns / that are inherently volatile between two copies —
// dropped before comparing (an id mismatch is expected, not a fidelity defect).
const VOLATILE = new Set([
  'id',
  'courseId',
  'lessonId',
  'globalBlockId',
  'originalId',
  'createdAt',
  'updatedAt',
  'contentUpdatedAt',
  'lastUpdatedBy',
  'transferredAt',
  'duplicatedFromId',
  'isNewlyInserted',
  'isPartnerContentAuthor',
  'pendingItemId',
  'version',
  'order',
  'author',
  'selectedAuthorId',
  'experiments',
  'metadata',
  'position',
  'deleted',
  'ready',
  // Server-DERIVED media delivery fields — regenerated by upload/CRUSH/TRANSCODE,
  // so they won't round-trip identically. Parity cares that the media KEY is
  // present (tokenized to #media), not these derivatives.
  'crushedKey',
  'useCrushedKey',
  'isSkipCrush',
  'sourcedFrom',
  'originalUrl',
  'thumbnail',
]);

// Long opaque server ids (course/lesson) aren't lowercase cuids — match them too
// so they normalize to the same token on both sides.
const RE_SERVER_ID = /^[A-Za-z0-9_-]{20,}$/;

function isIdLike(s: string): boolean {
  return looksLikeClientId(s) || RE_SERVER_ID.test(s);
}

function normalizeString(s: string): string {
  const kind = classifyString(s);
  if (kind && kind.startsWith('media-')) {
    // Any uploaded media key (old or new) → a presence token; we verify the slot
    // is filled, not the exact key (which is always remapped).
    return extractUploadedKeys(s).length ? '#media' : s;
  }
  // CDN / embed URLs are kept verbatim (they must round-trip exactly).
  if (kind === 'cdn' || kind === 'embed') return s;
  if (isIdLike(s)) return '#id';
  // Collapse insignificant whitespace (HTML/text re-serialization differences).
  return s.replace(/\s+/g, ' ').trim();
}

/** Canonicalize a value: drop volatile keys, tokenize ids/media, normalize text,
 *  sort object keys (so key-order differences don't show as diffs). */
export function canonicalize(node: unknown): unknown {
  if (node === null || node === undefined) return null;
  if (typeof node === 'string') return normalizeString(node);
  if (typeof node !== 'object') return node;
  if (Array.isArray(node)) return node.map(canonicalize);
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(node as Record<string, unknown>).sort()) {
    if (VOLATILE.has(k)) continue;
    out[k] = canonicalize((node as Record<string, unknown>)[k]);
  }
  return out;
}

export type ParityKind =
  | 'missing-lesson'
  | 'extra-lesson'
  | 'missing-block'
  | 'extra-block'
  | 'block-type-changed'
  | 'content-changed'
  | 'media-missing';

export interface ParityIssue {
  kind: ParityKind;
  /** Human path, e.g. `lessons[2] (Quiz) / blocks[5] interactive/tabs`. */
  path: string;
  detail?: string;
  /** Whether this divergence was expected (a flagged/unsupported case). */
  expected?: boolean;
}

export interface ParityReport {
  ok: boolean;
  lessons: { source: number; target: number };
  blocks: { source: number; target: number; compared: number };
  /** Real, unexpected divergences (drive ok=false). */
  issues: ParityIssue[];
  /** Expected divergences (flagged media not carried, draw-from-bank random draw). */
  expectedDivergences: ParityIssue[];
}

// Order lessons by the course's authoritative ordered lesson-id list
// (`course.lessons`) — the SAME ordering the plan builds with. ⚠ Do NOT sort by
// `position`: that field scrambles a real course (the very reason the plan stopped
// using it). Sorting either side by position aligns source-vs-target in different
// orders and manufactures phantom block-type-changed / missing-block divergences.
function orderedLessons(doc: GetCourseDocument): Lesson[] {
  const ls = Array.isArray(doc.lessons) ? doc.lessons : [];
  const orderField = (doc.course as Record<string, unknown> | undefined)?.lessons;
  return orderLessons(ls, orderField);
}

function blockKey(b: Block): string {
  return `${b.family ?? '?'}/${b.variant ?? b.type ?? '?'}`;
}

/** Collect leaf-level diffs between two canonical values, classifying a
 *  source-has-media / target-empty diff as `media-missing` (often expected). */
function collectLeafDiffs(
  a: unknown,
  b: unknown,
  path: string,
  out: { mediaMissing: string[]; changed: string[] },
): void {
  if (JSON.stringify(a) === JSON.stringify(b)) return;
  const aMedia = a === '#media';
  const bEmpty = b === '' || b === null || b === undefined;
  if (aMedia && bEmpty) {
    out.mediaMissing.push(path);
    return;
  }
  // Recurse into objects/arrays to localize the diff; leaf mismatch → changed.
  if (
    a && b && typeof a === 'object' && typeof b === 'object' &&
    Array.isArray(a) === Array.isArray(b)
  ) {
    if (Array.isArray(a) && Array.isArray(b)) {
      const n = Math.max(a.length, b.length);
      for (let i = 0; i < n; i++) collectLeafDiffs(a[i], b[i], `${path}[${i}]`, out);
      return;
    }
    const ao = a as Record<string, unknown>;
    const bo = b as Record<string, unknown>;
    for (const k of new Set([...Object.keys(ao), ...Object.keys(bo)])) {
      collectLeafDiffs(ao[k], bo[k], path ? `${path}.${k}` : k, out);
    }
    return;
  }
  out.changed.push(path);
}

/**
 * Compare an archived source course to a read-back target course. `flags` are
 * the import's manual-handling flags (storyline / orphan / unsupported media /
 * draw-from-bank) — divergences attributable to them are reported as *expected*
 * rather than failures.
 */
export function verifyParity(
  source: GetCourseDocument,
  target: GetCourseDocument,
  flags: ManualFlag[] = [],
): ParityReport {
  const sl = orderedLessons(source);
  const tl = orderedLessons(target);
  const issues: ParityIssue[] = [];
  const expected: ParityIssue[] = [];

  // A block is "media-tolerant" if the import flagged it (storyline / orphan) or
  // any course/lesson/theme/bank media was flagged unsupported.
  const flaggedBlockIds = new Set(
    flags.filter((f) => f.sourceBlockId).map((f) => f.sourceBlockId),
  );
  const hasUnsupportedMedia = flags.some((f) => f.kind === 'unsupported-media');
  const hasStoryline = flags.some((f) => f.kind === 'storyline');

  let blocksSource = 0;
  let blocksTarget = 0;
  let compared = 0;

  const nL = Math.max(sl.length, tl.length);
  for (let i = 0; i < nL; i++) {
    const s = sl[i];
    const t = tl[i];
    const label = `lessons[${i}]${s?.title ? ` (${s.title})` : ''}`;
    if (s && !t) {
      issues.push({ kind: 'missing-lesson', path: label, detail: 'lesson absent on target' });
      blocksSource += (s.items?.length ?? 0);
      continue;
    }
    if (!s && t) {
      issues.push({ kind: 'extra-lesson', path: `lessons[${i}]`, detail: 'unexpected lesson on target' });
      blocksTarget += (t.items?.length ?? 0);
      continue;
    }
    if (!s || !t) continue;

    if ((s.type ?? 'blocks') !== (t.type ?? 'blocks')) {
      issues.push({
        kind: 'content-changed',
        path: label,
        detail: `lesson type ${s.type} → ${t.type}`,
      });
    }

    const sb = (s.items ?? []) as Block[];
    const tb = (t.items ?? []) as Block[];
    blocksSource += sb.length;
    blocksTarget += tb.length;

    const nB = Math.max(sb.length, tb.length);
    for (let j = 0; j < nB; j++) {
      const a = sb[j];
      const b = tb[j];
      const bpath = `${label} / blocks[${j}]${a ? ` ${blockKey(a)}` : ''}`;
      if (a && !b) {
        issues.push({ kind: 'missing-block', path: bpath, detail: 'block absent on target' });
        continue;
      }
      if (!a && b) {
        issues.push({ kind: 'extra-block', path: `${label} / blocks[${j}] ${blockKey(b)}`, detail: 'unexpected block on target' });
        continue;
      }
      if (!a || !b) continue;
      compared++;

      if (blockKey(a) !== blockKey(b)) {
        issues.push({ kind: 'block-type-changed', path: bpath, detail: `${blockKey(a)} → ${blockKey(b)}` });
        continue;
      }

      const isDrawFromBank = blockKey(a) === 'knowledgeCheck/draw from question bank';
      const mediaTolerant =
        (a.id && flaggedBlockIds.has(a.id)) || hasUnsupportedMedia || hasStoryline;

      const diffs = { mediaMissing: [] as string[], changed: [] as string[] };
      collectLeafDiffs(canonicalize(a), canonicalize(b), '', diffs);

      for (const p of diffs.mediaMissing) {
        (mediaTolerant ? expected : issues).push({
          kind: 'media-missing',
          path: `${bpath}.${p}`,
          detail: 'media present in source, empty on target',
          expected: mediaTolerant,
        });
      }
      if (diffs.changed.length) {
        // A draw-from-bank block's bound question set is a random draw → tolerate.
        const bucket = isDrawFromBank ? expected : issues;
        bucket.push({
          kind: 'content-changed',
          path: bpath,
          detail: `${diffs.changed.length} field(s) differ: ${diffs.changed.slice(0, 6).join(', ')}`,
          expected: isDrawFromBank,
        });
      }
    }
  }

  return {
    ok: issues.length === 0,
    lessons: { source: sl.length, target: tl.length },
    blocks: { source: blocksSource, target: blocksTarget, compared },
    issues,
    expectedDivergences: expected,
  };
}

export function parityReportToMarkdown(r: ParityReport): string {
  const lines: string[] = [];
  lines.push(`## Read-back parity${r.ok ? ' — OK' : ' — DIVERGENCES'}`);
  lines.push(
    `- Lessons: ${r.lessons.source} source / ${r.lessons.target} target · ` +
      `Blocks: ${r.blocks.source} source / ${r.blocks.target} target (${r.blocks.compared} compared)`,
  );
  if (r.issues.length) {
    lines.push(`- **Unexpected divergences: ${r.issues.length}**`);
    for (const x of r.issues.slice(0, 25)) lines.push(`  - [${x.kind}] ${x.path}${x.detail ? ` — ${x.detail}` : ''}`);
  } else {
    lines.push('- Unexpected divergences: 0 ✓');
  }
  if (r.expectedDivergences.length) {
    lines.push(`- Expected divergences (flagged/random): ${r.expectedDivergences.length}`);
  }
  return lines.join('\n');
}
